---
- hosts: all
  remote_user: vagrant
  become_user: root
  become_method: sudo
  become: true

  tasks:
  - import_tasks: base-tasks-k8s.yaml

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --pod-network-cidr=172.48.0.0/16 --token-ttl=12h

  - name: Create kubeconfig local directory
    file:
      path: /home/vagrant/.kube
      state: directory
      mode: '0755'
    become: false

  - name: Copy system-wide kubeconfig to local user vagrant
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      remote_src: true

  - name: Change ownership of local kubeconfig
    file:
      path: /home/vagrant/.kube/config
      owner: vagrant
      group: vagrant

  - name: Copy all required YAML files
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'network-calico.yaml', dest: '/home/vagrant/network-calico.yaml' }
      - { src: 'metallb.yaml', dest: '/home/vagrant/metallb.yaml' }
      - { src: 'metallb-localnet.yaml', dest: '/home/vagrant/metallb-localnet.yaml' }
      - { src: 'traefik-namespace.yaml', dest: '/home/vagrant/traefik-namespace.yaml' }
      - { src: 'traefik-definition.yaml', dest: '/home/vagrant/traefik-definition.yaml' }
      - { src: 'traefik-rbac.yaml', dest: '/home/vagrant/traefik-rbac.yaml' }
      - { src: 'traefik-deployment.yaml', dest: '/home/vagrant/traefik-deployment.yaml' }
      - { src: 'traefik-ingress-dashboard.yaml', dest: '/home/vagrant/traefik-ingress-dashboard.yaml' }
      - { src: 'kubernetes-dashboard-v2rc5.yaml', dest: '/home/vagrant/kubernetes-dashboard-v2rc5.yaml' }
      - { src: 'kubernetes-dashboard-admin.yaml', dest: '/home/vagrant/kubernetes-dashboard-admin.yaml' }
    become: false

  - name: Install Calico, MetalLB, Traefik and the k8s Dashbooard
    command: kubectl create -f /home/vagrant/{{ item }}
    with_items:
    - network-calico.yaml
    - metallb.yaml
    - metallb-localnet.yaml
    - traefik-namespace.yaml
    - traefik-definition.yaml
    - traefik-rbac.yaml
    - traefik-deployment.yaml
    - traefik-ingress-dashboard.yaml
    - kubernetes-dashboard-v2rc5.yaml
    - kubernetes-dashboard-admin.yaml
    become: false

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command
    become: false

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
    become: false

  handlers:
  - import_tasks: base-handlers-k8s.yaml

