apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.25.210.0/24
      - 172.25.220.0/24
      - 172.25.230.0/24
      - 172.25.240.0/24
      - 172.25.250.0/24
      avoid-buggy-ips: true
