---
- hosts: all
  remote_user: vagrant
  become_user: root
  become_method: sudo
  become: true

  tasks:
  - import_tasks: base-tasks-k8s.yml

  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh

  handlers:
  - import_tasks: base-handlers-k8s.yml

